# Generated by Django 5.1.5 on 2025-02-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('victims', models.TextField(max_length=500)),
                ('open', models.BooleanField()),
                ('successful', models.BooleanField()),
                ('responsibility_of', models.CharField(max_length=100)),
            ],
        ),
    ]
