# Generated by Django 5.1.5 on 2025-02-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_crime_victims'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crime')),
            ],
        ),
    ]
